version: '3.4'

services:
  nginx:
    ports:
      - '3000:80'

  node-app:
    build:
      context: .
      args: 
        NODE_ENV: development
    volumes:
        - ./:/app
        - /app/node_modules
    environment: 
        - NODE_ENV=development
        - MONGO_USER=faiza4dev
        - MONGO_PASSWORD=rahasiaku
        - SESSION_SECRET=secret
    command:  npm run dev
  mongo:
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=faiza4dev
      - MONGO_INITDB_ROOT_PASSWORD=rahasiaku